project:
  type: website
  output-dir: docs
  
website:
  title: "Anonymized APSA DDRIG Grant Materials"
  navbar:
    left:
      - href: chap2.qmd
      - chap2_grants.qmd
  page-footer:
    right: ""
    left: "&copy; Copyright 2024"

format:
  html:
    theme: sandstone
    mainfont: Georgia
    title-block-banner-color: rgb(80, 0, 0)
    toc: true

editor: source

