project:
  type: website
  output-dir: docs
  
website:
  title: "Duncan Espenshade"
  navbar:
    logo: img/headshot.jpg
    left:
      - href: home.qmd
        text: Home
      - Research.qmd
      - teaching.qmd
      - CV.qmd
    tools:
      - text: Email
        href: "mailto:duncane98@tamu.edu"
      - icon: github
        href: https://github.com/espenshaded/website
  page-footer:
    right: ""
    left: "&copy; Copyright 2024, Duncan Espenshade"

format:
  html:
    theme: lumen
    mainfont: Georgia
    title-block-banner-color: rgb(80, 0, 0)
    toc: true

editor: source

