project:
  type: website
  output-dir: docs
  
website:
  title: "Anonymized APSA DDRIG Grant Materials"
  navbar:
    logo: img/headshot.jpg
    left:
      - href: home.qmd
        text: Home
      - Research.qmd
      - teaching.qmd
      - CV.qmd
  page-footer:
    right: ""
    left: "&copy; Copyright 2024"

format:
  html:
    theme: lumen
    mainfont: Georgia
    title-block-banner-color: rgb(80, 0, 0)
    toc: true

editor: source

